//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activities.
        /// </summary>
        internal static string ActivitiesLink {
            get {
                return ResourceManager.GetString("ActivitiesLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address:.
        /// </summary>
        internal static string AddressLbl {
            get {
                return ResourceManager.GetString("AddressLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to Food &amp; Film Ticket.
        /// </summary>
        internal static string AddToFFLbl {
            get {
                return ResourceManager.GetString("AddToFFLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to Wishlist.
        /// </summary>
        internal static string AddWishlistBtn {
            get {
                return ResourceManager.GetString("AddWishlistBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kijkwijzer®.
        /// </summary>
        internal static string AgeClassificationLbl {
            get {
                return ResourceManager.GetString("AgeClassificationLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author:.
        /// </summary>
        internal static string AuthorLbl {
            get {
                return ResourceManager.GetString("AuthorLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cast:.
        /// </summary>
        internal static string CastLbl {
            get {
                return ResourceManager.GetString("CastLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code:.
        /// </summary>
        internal static string CodeLbl {
            get {
                return ResourceManager.GetString("CodeLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your order has been confirmed..
        /// </summary>
        internal static string ConfirmedTxt {
            get {
                return ResourceManager.GetString("ConfirmedTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        internal static string ContactLbl {
            get {
                return ResourceManager.GetString("ContactLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description:.
        /// </summary>
        internal static string DescriptionLbl {
            get {
                return ResourceManager.GetString("DescriptionLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Director:.
        /// </summary>
        internal static string DirectorLbl {
            get {
                return ResourceManager.GetString("DirectorLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can choose to send your reservation per email.
        /// </summary>
        internal static string EmailCodeTxt {
            get {
                return ResourceManager.GetString("EmailCodeTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Haarlem has an exquisite culinary culture, that is why we selected the best restaurants too take part in this years festival. To promote these restaurants we bring you the Food &amp; Film Ticket. Dining as the appetiser and a beautiful movie as a dessert.&lt;/p&gt;
        ///&lt;p&gt;A Food &amp; Film ticket will save you some money and introduces you to the finest restaurants in the area. To order a Food &amp; Film Ticket, navagate to the movie you would like to see and open its details page. From this page you will have the option to o [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FoodFilmContent {
            get {
                return ResourceManager.GetString("FoodFilmContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Food &amp; Film Ticket.
        /// </summary>
        internal static string FoodFilmTitle {
            get {
                return ResourceManager.GetString("FoodFilmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To choice your movie go to the.
        /// </summary>
        internal static string FoodFilmTxt1 {
            get {
                return ResourceManager.GetString("FoodFilmTxt1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to page..
        /// </summary>
        internal static string FoodFilmTxt2 {
            get {
                return ResourceManager.GetString("FoodFilmTxt2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restaurants.
        /// </summary>
        internal static string FoodLbl {
            get {
                return ResourceManager.GetString("FoodLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Food.
        /// </summary>
        internal static string FoodLink {
            get {
                return ResourceManager.GetString("FoodLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friday.
        /// </summary>
        internal static string Friday {
            get {
                return ResourceManager.GetString("Friday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Wishlist.
        /// </summary>
        internal static string GetWishlistLbl {
            get {
                return ResourceManager.GetString("GetWishlistLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Haarlem.
        /// </summary>
        internal static string HaarlemLink {
            get {
                return ResourceManager.GetString("HaarlemLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haarlem is the sixth monument city of the Netherlands. The city has 1149 listed buildings. In the city also stand most of the monuments, such as the Grote Kerk, City Hall and the meat market. However, the city also has a number of leading modern buildings like the Toneelschuur, Patronaat and the construction of Stadsschouwburg. The two best known churches in Haarlem, the &apos;Grote Kerk&apos;, built between 1370 and 1520 and the &apos;Cathedral of St Bavo&apos;, built in 1930. Since both churches bear the sacred name &apos;Bavo&apos;,  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HaarlemTxt {
            get {
                return ResourceManager.GetString("HaarlemTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Welcome to Haarlem and welcome to the international Haarlem film festival. This year’s theme is The Science of Fiction / Celluloid Realism. &lt;/p&gt;
        ///&lt;p&gt;
        ///Ever since Georges Méliès, film is pre- eminently the medium where experiments and vision go hand in hand. Countless directors envisioned with their films a future in which mechanisation and technology are omnipresent. And always the questions are the same: “In what way do man and machine influence each other and how does that affect our society”. &lt;/p&gt;
        ///&lt;p&gt;
        ///O [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HomeContent {
            get {
                return ResourceManager.GetString("HomeContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduction.
        /// </summary>
        internal static string HomeTitle {
            get {
                return ResourceManager.GetString("HomeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IMDB Page:.
        /// </summary>
        internal static string ImdbPageLbl {
            get {
                return ResourceManager.GetString("ImdbPageLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IMDB Rating:.
        /// </summary>
        internal static string ImdbRatingLbl {
            get {
                return ResourceManager.GetString("ImdbRatingLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NL.
        /// </summary>
        internal static string LanguageLbl {
            get {
                return ResourceManager.GetString("LanguageLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location:.
        /// </summary>
        internal static string LocationLbl {
            get {
                return ResourceManager.GetString("LocationLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location and Time:.
        /// </summary>
        internal static string LocationTimeLbl {
            get {
                return ResourceManager.GetString("LocationTimeLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movies.
        /// </summary>
        internal static string MovieLink {
            get {
                return ResourceManager.GetString("MovieLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movies.
        /// </summary>
        internal static string MoviesLbl {
            get {
                return ResourceManager.GetString("MoviesLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Food &amp; Film Ticket.
        /// </summary>
        internal static string OrderFFBtn {
            get {
                return ResourceManager.GetString("OrderFFBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overview.
        /// </summary>
        internal static string Overview {
            get {
                return ResourceManager.GetString("Overview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Succeeded.
        /// </summary>
        internal static string PaymentTitle {
            get {
                return ResourceManager.GetString("PaymentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phonenumber:.
        /// </summary>
        internal static string PhoneLbl {
            get {
                return ResourceManager.GetString("PhoneLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place Order.
        /// </summary>
        internal static string PlaceOrderLbl {
            get {
                return ResourceManager.GetString("PlaceOrderLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price:.
        /// </summary>
        internal static string PriceLbl {
            get {
                return ResourceManager.GetString("PriceLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        internal static string ResAmountLbl {
            get {
                return ResourceManager.GetString("ResAmountLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make Reservation.
        /// </summary>
        internal static string ResBtn {
            get {
                return ResourceManager.GetString("ResBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take note of this code.
        /// </summary>
        internal static string ResCodeTxt1 {
            get {
                return ResourceManager.GetString("ResCodeTxt1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to as this will be the way to retrieve your tickets..
        /// </summary>
        internal static string ResCodeTxt2 {
            get {
                return ResourceManager.GetString("ResCodeTxt2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Or print it directly from our page..
        /// </summary>
        internal static string ResCodeTxt3 {
            get {
                return ResourceManager.GetString("ResCodeTxt3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        internal static string ResCustomerNameLbl {
            get {
                return ResourceManager.GetString("ResCustomerNameLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phonenumber:.
        /// </summary>
        internal static string ResCustomerPhoneLbl {
            get {
                return ResourceManager.GetString("ResCustomerPhoneLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date - Time.
        /// </summary>
        internal static string ResDateTimeLbl {
            get {
                return ResourceManager.GetString("ResDateTimeLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservations.
        /// </summary>
        internal static string ReservationsTitle {
            get {
                return ResourceManager.GetString("ReservationsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        internal static string ResLocationLbl {
            get {
                return ResourceManager.GetString("ResLocationLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string ResNameLbl {
            get {
                return ResourceManager.GetString("ResNameLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a method of payment.
        /// </summary>
        internal static string ResPaymentOptionsLbl {
            get {
                return ResourceManager.GetString("ResPaymentOptionsLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide a name please.
        /// </summary>
        internal static string ResProvideName {
            get {
                return ResourceManager.GetString("ResProvideName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide a Phonenumber please.
        /// </summary>
        internal static string ResProvidePhone {
            get {
                return ResourceManager.GetString("ResProvidePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Price.
        /// </summary>
        internal static string ResTotalPriceLbl {
            get {
                return ResourceManager.GetString("ResTotalPriceLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturday.
        /// </summary>
        internal static string Saturday {
            get {
                return ResourceManager.GetString("Saturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save this item in your wishlist?.
        /// </summary>
        internal static string SaveOrderWishlistLbl {
            get {
                return ResourceManager.GetString("SaveOrderWishlistLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specials.
        /// </summary>
        internal static string SpecialsLbl {
            get {
                return ResourceManager.GetString("SpecialsLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunday.
        /// </summary>
        internal static string Sunday {
            get {
                return ResourceManager.GetString("Sunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thursday.
        /// </summary>
        internal static string Thursday {
            get {
                return ResourceManager.GetString("Thursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time and Date:.
        /// </summary>
        internal static string TimeDateLbl {
            get {
                return ResourceManager.GetString("TimeDateLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time:.
        /// </summary>
        internal static string TimeLbl {
            get {
                return ResourceManager.GetString("TimeLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title:.
        /// </summary>
        internal static string TitleLbl {
            get {
                return ResourceManager.GetString("TitleLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Price:.
        /// </summary>
        internal static string TotalPriceLbl {
            get {
                return ResourceManager.GetString("TotalPriceLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wednesday.
        /// </summary>
        internal static string Wednesday {
            get {
                return ResourceManager.GetString("Wednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you&apos;ve got an whislist code, you can enter it below..
        /// </summary>
        internal static string WishlistCode {
            get {
                return ResourceManager.GetString("WishlistCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is your wishlist, it is empty at the moment. You can add.
        /// </summary>
        internal static string WishlistTxt1 {
            get {
                return ResourceManager.GetString("WishlistTxt1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and.
        /// </summary>
        internal static string WishlistTxt2 {
            get {
                return ResourceManager.GetString("WishlistTxt2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to your wishlist by clicking the add to wishlist button..
        /// </summary>
        internal static string WishlistTxt3 {
            get {
                return ResourceManager.GetString("WishlistTxt3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year:.
        /// </summary>
        internal static string YearLbl {
            get {
                return ResourceManager.GetString("YearLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZipCode:.
        /// </summary>
        internal static string ZipCodeLbl {
            get {
                return ResourceManager.GetString("ZipCodeLbl", resourceCulture);
            }
        }
    }
}
